name: Resharper Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.101
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Run resharper inspection
        run: jb inspectcode AssistPurchaseCaseStudy.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder AssistPurchaseCaseStudy.sln /output=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1
